name: C/C++ CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install lv2-dev libgtkmm-2.4-dev qt5-qmake qt5-default
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - uses: actions/upload-artifact@v1
      with:
        name: abGate.lv2
        path: /usr/lib/lv2/abGate.lv2
